API_PORT
LOG_LEVEL

MAINTENANCE_LOCKFILE
LAST_UPDATE_FILE
MAINTENANCE_MESSAGE

BASE_URL
API_BASE_PATH

DATABASE_HOST
DATABASE_PORT
DATABASE_NAME
DATABASE_TYPE
DATABASE_USER
DATABASE_PASSWORD
DATABASE_MIGRATIONS_TABLE
