port: API_PORT
logLevel: LOG_LEVEL

misc:
  lockfile: MAINTENANCE_LOCKFILE
  maintenanceNotification: MAINTENANCE_MESSAGE

token:
  expiry: TOKEN_EXPIRY_LENGTH

url:
  basePath: BASE_URL
  apiPath: API_BASE_PATH

database:
  database: DATABASE_NAME
  username: DATABASE_USER
  password: DATABASE_PASSWORD

defaults:
  username: DEFAULT_USERNAME
  password: DEFAULT_PASSWORD