port: 3000
logLevel: debug

url:
  basePath: http://localhost:3000
  apiPath: ''

misc:
  lockfile: maintenance.lock
  maintenanceNotification: "API in maintenance mode."
  lastUpdateFile: .last-update
  changelogFile: CHANGELOG.md

token:
  expiry: 1h
  key: ./volumes/app.key
  bits: 128

frontend:
  dir: static

swagger:
  path: /internal/docs
  title: waky
  description: API
  useHttps: false

database:
  database: volumes/db.db
  type: better-sqlite3
  port: 3306
  username: user
  password: secret
  synchronize: false
  cache: false
  keepConnectionAlive: true
  autoLoadEntities: true
  mock:
    database: volumes/mock.db
  directories:
    entity: '**/*.entity{.ts,.js}'
    migration: migrations
    seed: seeds

defaults:
  username: admin
  password: admin
